# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Command

# Model Form Field configuration
form: $/awebsome/remotessh/models/command/fields.yaml

# Model Class name
modelClass: Awebsome\Remotessh\Models\Command

# Default redirect location
defaultRedirect: awebsome/remotessh/commands

# Create page
create:
    title: Create Command
    redirect: awebsome/remotessh/commands/update/:id
    redirectClose: awebsome/remotessh/commands

# Update page
update:
    title: Edit Command
    redirect: awebsome/remotessh/commands
    redirectClose: awebsome/remotessh/commands

# Preview page
preview:
    title: Preview Command
